apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml
images:
- name: harbor.teamgamdom.com/gamdom/images/staging
  newTag: pr-2911-eng-2763-users-can-comple
