name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    env: # Define environment variables for the entire job
      NODE_ENV: ${{ secrets.ENVIRONMENT }}
      APP_VERSION: ${{ secrets.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Print environment variables
        run: echo "Environment is $NODE_ENV and version is $APP_VERSION"
